name: smart_car_park # Your App Name
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.3
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  geolocator: ^11.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.6.1
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.0
  intl: ^0.19.0
  location: ^6.0.1
  logger: ^2.2.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/register_images/
    - assets/images/lottie/
    - assets/images/markers/
    - assets/icons/
  # Fonts Assets
  fonts:
    - family: Goran
      fonts:
        - asset: assets/fonts/KGoran.ttf
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
    - family: Peshang
      fonts:
        - asset: assets/fonts/Peshang_Des_5_Bold.ttf
    - family: Rabar
      fonts:
        - asset: assets/fonts/Rabar_021.ttf
